### ISSUE TITLE
April Roadmap

### ISSUE THREAD

**Issue by mahaloz** [mahaloz/decompilation-wiki#1]
The decompilation Wiki started this month and it's only missing one thing... CONTENT! Luckily, most of the content has already been found. Now it just needs to be categorized. 

For my PhD comprehensive exam, I've collected a series of [72 Citations](https://docs.google.com/spreadsheets/d/1kY_yuFfAqLdIDLuNiBuuuEihE-lkd_G9Fp2UiV2TEOk/edit?usp=sharing). These papers call all fit under some category shown below. This will hopefully be all done by April 29th. After that, the Wiki will be open to more content submissions. 

### Categories
- Decompilers
	- Directory
	- Tools & Plugins
- Fundamentals
	- Control Flow Graph Recovery
		- Disassembly
		- Lifting
		- Indirect Jump Resolving
	- Control Flow Structuring 
		- General Techniques
			- Schema-matching
			- Condition-based
		- Region Identification
	- Datatype Recovery
		- Type recovery
		- Structure recovery 
	- Evaluation
		- Measuring decompilation
- Application Research
	- Symbol Recovery 
		- Variables
		- Functions
	- Function Identification
	- Program similarity
	- Inlining
- Applications
	- Recompilation
		- Videogames

## TODO
- [ ] Decompiler Listing
- [ ] CF Recovery section
- [ ] Type recovery section
- [ ] CFG recovery section
- [ ] Evall section
- [ ] Application Research 
- [ ] Applictions
- [ ] Contribution Guide

**Comment by mahaloz** [comment]
Completed and new TODOs created to track unfinished or needed work
